### ISSUE TITLE
[Feature Request] Allow allowChildFolder

### ISSUE THREAD

**Issue by donaldpipowitch** [MelvinVermeer/eslint-plugin-no-relative-import-paths#20]
Thank you for the package! It would be lovely if next to `allowSameFolder` which allows `import Something from "./something";
` an `allowChildFolder` option would exists that allows `import Something from "./some-child/something";`. ❤️

**Comment by rh-meowsa** [comment]
@MelvinVermeer what do you think about adding this?

**Comment by rh-meowsa** [comment]
This is already the behavior with `allowSameFolder`

see https://github.com/MelvinVermeer/eslint-plugin-no-relative-import-paths/blob/main/index.js#L14
