### ISSUE TITLE
v1.1.0 breaks support for ESLint 8.x

### ISSUE THREAD

**Issue by chrisshiplet** [MelvinVermeer/eslint-plugin-no-relative-import-paths#3]
Hello! v1.0.8 of this library works great with ESLint 8, but unfortunately v1.1.0 broke compatibility due to #2

https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#rules-require-metafixable-to-provide-fixes

```
Oops! Something went wrong! :(

ESLint: 8.6.0

Error: Fixable rules must set the `meta.fixable` property to "code" or "whitespace".
Occurred while linting
Rule: "no-relative-import-paths/no-relative-import-paths"
```

**Comment by MelvinVermeer** [comment]
Thanks for reporting, I will look in to this soon.

**Comment by MelvinVermeer** [comment]
Fixed in latest release: https://github.com/MelvinVermeer/eslint-plugin-no-relative-import-paths/releases/tag/1.2.0
