### ISSUE TITLE
New versions not pushed to NPM

### ISSUE THREAD

**Issue by tdymel** [MelvinVermeer/eslint-plugin-no-relative-import-paths#8]
Hi!
You are probably aware, but current versions are not pushed to NPM. The pipeline seems to be broken.

I would look forward to version 1.3, since there the path formatting for windows was fixed, which is required in the project Im working on, as there are also people with windows working on it.

Thanks for making this plugin!

**Comment by MelvinVermeer** [comment]
Hi there 👋 ,

Thanks for reporting.

There was an issue with the npm access token, this is fixed now, I have published 1.3.2 now.


https://www.npmjs.com/package/eslint-plugin-no-relative-import-paths/v/1.3.2
